import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { FaGithub, FaLinkedin } from "react-icons/fa";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Yee Yang's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-900 text-white scroll-smooth`}
      >
        {/* Navbar */}
        <nav className="sticky top-0 z-50 bg-gray-950 bg-opacity-90 backdrop-blur-md px-6 py-4 flex items-center justify-between shadow-md">
          <div className="text-xl font-bold">Yee Yang Kok</div>
          <div className="flex items-center gap-6 text-sm font-medium">
            <a href="#introduction" className="hover:text-blue-400 transition">
              Introduction
            </a>
            <a href="#experience" className="hover:text-blue-400 transition">
              Experience
            </a>
            <a href="#projects" className="hover:text-blue-400 transition">
              Projects
            </a>
            <a href="#education" className="hover:text-blue-400 transition">
              Education
            </a>
            <a
              href="https://github.com/kokyeeyang"
              target="_blank"
              rel="noopener noreferrer"
              className="hover:text-blue-400 transition"
              aria-label="GitHub"
            >
              <FaGithub size={20} />
            </a>
            <a
              href="https://linkedin.com/in/yee-yang-kok"
              target="_blank"
              rel="noopener noreferrer"
              className="hover:text-blue-400 transition"
              aria-label="LinkedIn"
            >
              <FaLinkedin size={20} />
            </a>
          </div>
        </nav>

        {/* Main Page Content */}
        {children}
      </body>
    </html>
  );
}
